# Generated by Django 2.2.4 on 2019-08-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0004_remove_enterprises_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='Region',
        ),
    ]
