# Generated by Django 2.2.4 on 2019-08-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0005_auto_20190818_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprises',
            name='product',
            field=models.ManyToManyField(to='ts.Product', verbose_name='продукты'),
        ),
        migrations.AlterField(
            model_name='enterprises',
            name='netenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts.NetEnterprises', verbose_name='сеть предприятий'),
        ),
        migrations.AlterField(
            model_name='enterprises',
            name='region',
            field=models.ManyToManyField(to='ts.Region', verbose_name='Районы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell',
            field=models.ManyToManyField(to='ts.NetEnterprises', verbose_name='сеть предприятий'),
        ),
    ]
