# Generated by Django 2.2.4 on 2019-08-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0006_auto_20190818_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprises',
            name='product',
        ),
        migrations.AlterField(
            model_name='enterprises',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Предприятие'),
        ),
    ]
